#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v12
# autospec commit: f9eab48
#
Name     : qt6shadertools
Version  : 6.7.2
Release  : 14
URL      : https://download.qt.io/official_releases/qt/6.7/6.7.2/submodules/qtshadertools-everywhere-src-6.7.2.zip
Source0  : https://download.qt.io/official_releases/qt/6.7/6.7.2/submodules/qtshadertools-everywhere-src-6.7.2.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qt6shadertools-lib = %{version}-%{release}
Requires: qt6shadertools-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# News
1. [As discussed in #3107](https://github.com/KhronosGroup/glslang/issues/3107), the default branch of this repository is now 'main'. This change should be transparent to repository users, since github rewrites many references to the old 'master' branch to 'main'. However, if you have a checked-out local clone, you may wish to take the following steps as recommended by github:

%package dev
Summary: dev components for the qt6shadertools package.
Group: Development
Requires: qt6shadertools-lib = %{version}-%{release}
Provides: qt6shadertools-devel = %{version}-%{release}
Requires: qt6shadertools = %{version}-%{release}

%description dev
dev components for the qt6shadertools package.


%package lib
Summary: lib components for the qt6shadertools package.
Group: Libraries
Requires: qt6shadertools-license = %{version}-%{release}

%description lib
lib components for the qt6shadertools package.


%package license
Summary: license components for the qt6shadertools package.
Group: Default

%description license
license components for the qt6shadertools package.


%prep
%setup -q -n qtshadertools-everywhere-src-6.7.2
cd %{_builddir}/qtshadertools-everywhere-src-6.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718925270
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1718925270
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6shadertools
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/79453f55fa8ee32d7b95581473edcbfd043e088f || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/dc8f2e570bf431427dbc3bab9d4d551b53a60208 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/7713a1753ce88f2c7e6b054ecc8e4c786df76300 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/c70af14df11e3908dfc10397b1ba4b1f346661f3 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/src/3rdparty/SPIRV-Cross/LICENSE %{buildroot}/usr/share/package-licenses/qt6shadertools/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/src/3rdparty/glslang/LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/c9b0324b816f3c220fc2885fa888c047de91abcb || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/QtShaderTools/6.7.2/QtShaderTools/private/qshaderrewriter_p.h
/usr/include/QtShaderTools/6.7.2/QtShaderTools/private/qspirvcompiler_p.h
/usr/include/QtShaderTools/6.7.2/QtShaderTools/private/qspirvshader_p.h
/usr/include/QtShaderTools/6.7.2/QtShaderTools/private/qspirvshaderremap_p.h
/usr/include/QtShaderTools/6.7.2/QtShaderTools/private/qtshadertoolsexports_p.h
/usr/include/QtShaderTools/6.7.2/QtShaderTools/private/qtshadertoolsglobal_p.h
/usr/include/QtShaderTools/6.7.2/QtShaderTools/rhi/qshaderbaker.h
/usr/include/QtShaderTools/QtShaderTools
/usr/include/QtShaderTools/QtShaderToolsDepends
/usr/include/QtShaderTools/QtShaderToolsVersion
/usr/include/QtShaderTools/qtshadertoolsexports.h
/usr/include/QtShaderTools/qtshadertoolsglobal.h
/usr/include/QtShaderTools/qtshadertoolsversion.h
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtShaderToolsTestsConfig.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsConfig.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsConfigVersion.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsDependencies.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsTargets.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsVersionlessTargets.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsConfig.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsConfigVersion.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsDependencies.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsTargets.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsVersionlessTargets.cmake
/usr/lib64/libQt6ShaderTools.prl
/usr/lib64/libQt6ShaderTools.so
/usr/lib64/pkgconfig/Qt6ShaderTools.pc
/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools_private.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libQt6ShaderTools.so.6.7.2
/V3/usr/lib64/qt6/bin/qsb
/usr/lib64/libQt6ShaderTools.so.6
/usr/lib64/libQt6ShaderTools.so.6.7.2
/usr/lib64/qt6/bin/qsb
/usr/lib64/qt6/metatypes/qt6shadertools_relwithdebinfo_metatypes.json
/usr/lib64/qt6/modules/ShaderTools.json

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6shadertools/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/qt6shadertools/7713a1753ce88f2c7e6b054ecc8e4c786df76300
/usr/share/package-licenses/qt6shadertools/79453f55fa8ee32d7b95581473edcbfd043e088f
/usr/share/package-licenses/qt6shadertools/c70af14df11e3908dfc10397b1ba4b1f346661f3
/usr/share/package-licenses/qt6shadertools/c9b0324b816f3c220fc2885fa888c047de91abcb
/usr/share/package-licenses/qt6shadertools/dc8f2e570bf431427dbc3bab9d4d551b53a60208
