#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v23
# autospec commit: 936534a
#
Name     : qt6shadertools
Version  : 6.9.0
Release  : 23
URL      : https://download.qt.io/official_releases/qt/6.9/6.9.0/submodules/qtshadertools-everywhere-src-6.9.0.tar.xz
Source0  : https://download.qt.io/official_releases/qt/6.9/6.9.0/submodules/qtshadertools-everywhere-src-6.9.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0 MIT
Requires: qt6shadertools-lib = %{version}-%{release}
Requires: qt6shadertools-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
![Continuous Integration](https://github.com/KhronosGroup/glslang/actions/workflows/continuous_integration.yml/badge.svg)
![Continuous Deployment](https://github.com/KhronosGroup/glslang/actions/workflows/continuous_deployment.yml/badge.svg)
[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/KhronosGroup/glslang/badge)](https://securityscorecards.dev/viewer/?uri=github.com/KhronosGroup/glslang)

%package dev
Summary: dev components for the qt6shadertools package.
Group: Development
Requires: qt6shadertools-lib = %{version}-%{release}
Provides: qt6shadertools-devel = %{version}-%{release}
Requires: qt6shadertools = %{version}-%{release}

%description dev
dev components for the qt6shadertools package.


%package lib
Summary: lib components for the qt6shadertools package.
Group: Libraries
Requires: qt6shadertools-license = %{version}-%{release}

%description lib
lib components for the qt6shadertools package.


%package license
Summary: license components for the qt6shadertools package.
Group: Default

%description license
license components for the qt6shadertools package.


%prep
%setup -q -n qtshadertools-everywhere-src-6.9.0
cd %{_builddir}/qtshadertools-everywhere-src-6.9.0
pushd ..
cp -a qtshadertools-everywhere-src-6.9.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1743630095
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1743630095
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6shadertools
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/Apache-2.0.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/be561fe6eb626c2566b9a6c0885554b4ee4e6b74 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/b073f11f0c81a95ab5e32aa6b5d23a5955a95274 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/GFDL-1.3-no-invariants-only.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/715f995f11805ee85601834220c43b082f457ea3 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/f45ee1c765646813b442ca58de72e20a64a7ddba || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/LICENSES/MIT.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/9b358a3bb3c510255f375406df8ce40d7e83edfb || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/src/3rdparty/SPIRV-Cross/LICENSE %{buildroot}/usr/share/package-licenses/qt6shadertools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qtshadertools-everywhere-src-%{version}/src/3rdparty/glslang/LICENSE.txt %{buildroot}/usr/share/package-licenses/qt6shadertools/f77668fa8c7bb3dc2788af730150c401bd723fed || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/QtShaderTools/6.9.0/QtShaderTools/private/qshaderrewriter_p.h
/usr/include/QtShaderTools/6.9.0/QtShaderTools/private/qspirvcompiler_p.h
/usr/include/QtShaderTools/6.9.0/QtShaderTools/private/qspirvshader_p.h
/usr/include/QtShaderTools/6.9.0/QtShaderTools/private/qspirvshaderremap_p.h
/usr/include/QtShaderTools/6.9.0/QtShaderTools/private/qtshadertoolsglobal_p.h
/usr/include/QtShaderTools/6.9.0/QtShaderTools/rhi/qshaderbaker.h
/usr/include/QtShaderTools/QtShaderTools
/usr/include/QtShaderTools/QtShaderToolsDepends
/usr/include/QtShaderTools/QtShaderToolsVersion
/usr/include/QtShaderTools/qtshadertoolsexports.h
/usr/include/QtShaderTools/qtshadertoolsglobal.h
/usr/include/QtShaderTools/qtshadertoolsversion.h
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtShaderToolsTestsConfig.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsConfig.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsConfigVersion.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsDependencies.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsTargets.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsVersionlessAliasTargets.cmake
/usr/lib64/cmake/Qt6ShaderTools/Qt6ShaderToolsVersionlessTargets.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateConfig.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateDependencies.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateTargets.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateVersionlessAliasTargets.cmake
/usr/lib64/cmake/Qt6ShaderToolsPrivate/Qt6ShaderToolsPrivateVersionlessTargets.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsMacros.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsConfig.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsConfigVersion.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsDependencies.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsTargets.cmake
/usr/lib64/cmake/Qt6ShaderToolsTools/Qt6ShaderToolsToolsVersionlessTargets.cmake
/usr/lib64/libQt6ShaderTools.prl
/usr/lib64/libQt6ShaderTools.so
/usr/lib64/pkgconfig/Qt6ShaderTools.pc
/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_shadertools_private.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libQt6ShaderTools.so.6.9.0
/V3/usr/lib64/qt6/bin/qsb
/usr/lib64/libQt6ShaderTools.so.6
/usr/lib64/libQt6ShaderTools.so.6.9.0
/usr/lib64/qt6/bin/qsb
/usr/lib64/qt6/metatypes/qt6shadertools_relwithdebinfo_metatypes.json
/usr/lib64/qt6/modules/ShaderTools.json
/usr/lib64/qt6/sbom/qtshadertools-6.9.0.spdx

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6shadertools/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/qt6shadertools/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qt6shadertools/715f995f11805ee85601834220c43b082f457ea3
/usr/share/package-licenses/qt6shadertools/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qt6shadertools/9b358a3bb3c510255f375406df8ce40d7e83edfb
/usr/share/package-licenses/qt6shadertools/b073f11f0c81a95ab5e32aa6b5d23a5955a95274
/usr/share/package-licenses/qt6shadertools/be561fe6eb626c2566b9a6c0885554b4ee4e6b74
/usr/share/package-licenses/qt6shadertools/f45ee1c765646813b442ca58de72e20a64a7ddba
/usr/share/package-licenses/qt6shadertools/f77668fa8c7bb3dc2788af730150c401bd723fed
